### ISSUE TITLE
Review strict Dockle scan during GitHub action: push.yml

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/docker-images#19]
Some of the images in this repository fail the `push.yml` build process due to Dockle scan errors. If the error exists in our `Dockerfile`s it is easily fixable. However if it exists in a required non-SLATE base image it may not.

A current example of this is our `perfsonar-checker` image. During a [GitHub action](https://github.com/slateci/docker-images/runs/5208331692?check_suite_focus=true) the following errors were produced by the `perfsonar/testpoint:v4.3.4` base image.

```bash
>>>> Dockle Scan <<<<
  FATAL	- CIS-DI-0009: Use COPY instead of ADD in Dockerfile
  	* Use COPY : /bin/sh -c #(nop) ADD file:cbb94d8ed6ae2e0a01f1907aa8dedc6ce153ca0b25a46db2468c92018dd33642 in /etc/supervisord.conf
```

The offending `ADD` can be seen in their [perfsonar-testpoint-docker](https://github.com/perfsonar/perfsonar-testpoint-docker) repository.

Let's review the strict nature of the Dockle scans and think about ways of working through issues like the above where our team has little to no control over the base image. Adding @amblinalong as a watcher.

**Comment by SamratAmate** [comment]
Provisioned .docklyignore and .trivyignore files for users to skip any specific vulnerability checksums. https://github.com/slateci/docker-images/pull/21 is merged. Closing this issue.
