### ISSUE TITLE
Integrate with slateci/slate-catalog

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/docker-images#24]

**Comment by cnweaver** [comment]
It's always been a bit unclear to me why this repository exists; it seems to just duplicate a subset of the catalog's functionality. Surely it would make more sense to fold it back into the catalog repo where it belongs?

**Comment by adamhgriffith-uofu** [comment]
Will be playing with keeping images together with the charts in https://github.com/slateci/slate-catalog-incubator/issues/13.
